/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rummikubkendall;

import javax.swing.JOptionPane;

/**
 *
 * @author kenda
 */
public class VistaFicha extends javax.swing.JPanel {

    private Ficha ficha;
    private PantallaJuego pantallaJuego;

    public VistaFicha(Ficha ficha, PantallaJuego pantallaJuego) {
        this.ficha = ficha;
        this.pantallaJuego = pantallaJuego;
        initComponents(); 
        postInitSetup();

    }

    public VistaFicha(Ficha ficha) {
        this(ficha, null); // Llama al otro constructor con null
    }

    // Configuración posterior al initComponents
    private void postInitSetup() {
        //configurar visualización del comodín
        if (ficha.isComodin()) {
            jLabel2.setText(""); // Texto vacío para comodines
        }

        // agregar MouseListener personalizado
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (ficha.isComodin()) {
                    handleComodinClick();
                }
                if (pantallaJuego != null) {
                    pantallaJuego.setFichaSeleccionada(VistaFicha.this);
                }
            }
        });
    }

    // Manejo del clic en comodín
    private void handleComodinClick() {
        String input = JOptionPane.showInputDialog(
                this,
                "Asigne valor al comodín (1-13):",
                "Valor del Comodín",
                JOptionPane.PLAIN_MESSAGE
        );

        try {
            if (input != null && !input.isEmpty()) {
                int value = Integer.parseInt(input);
                if (value >= 1 && value <= 13) {
                    ficha.setValorTemporal(value);
                } else {
                    showError("El valor debe estar entre 1 y 13");
                }
            }
        } catch (NumberFormatException e) {
            showError("Ingrese un número válido");
        }
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(
                this,
                message,
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    public Ficha getFicha() {
        return ficha;
    }

    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rummikubkendall/"+getFicha().getColor()+".png")));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(getFicha().getNumero()+"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
